name: Build and Upload Rust Binary

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install Rust toolchain
      uses: actions-rs/toolchain@v1
      with:
          toolchain: stable
          profile: minimal
          override: true

    - name: Build Rust Binary for Release
      run: |
        cd rust_sqlite_cli
        cargo build --release

    - name: Upload Binary as Artifact
      uses: actions/upload-artifact@v2
      with:
        name: rust-sqlite-cli-binary
        path: rust_sqlite_cli/target/release/rust_sqlite_cli
